DROP TABLE SOCX;
DROP TABLE INDX;
DROP TABLE PRODX;

CREATE TABLE IF NOT EXISTS SOCX (
    NUMSOC INT PRIMARY KEY,
    CP VARCHAR2(5)
);

CREATE TABLE IF NOT EXISTS INDX (
    NUMIND INT PRIMARY KEY,
    NUMSOC INT,
    FONCTION VARCHAR2(2)
);

CREATE TABLE IF NOT EXISTS PRODX (
    NUMSOC INT,
    NUMIND INT,
    CODE_PROD VARCHAR2(1),
    DATE_ACHAT DATE
);